[project_id]
cleaneazy-laundry = "jcckvihjumqdmkcbaebo"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.manage-staff]
verify_jwt = true
